package interfaces;

import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.JCheckBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pedro
 */
public class SalonHabana extends javax.swing.JDialog {

    /**
     * Creates new form SalonHabana
     */
    public SalonHabana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jDateChooserFecha.getDateEditor().setEnabled(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NombreCliente = new javax.swing.JLabel();
        TelefonoCliente = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        LabelApellido1 = new javax.swing.JLabel();
        Apellido1 = new javax.swing.JTextField();
        LabelApellido2 = new javax.swing.JLabel();
        Apellido2 = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelPersonas = new javax.swing.JLabel();
        jTextFieldPersonas = new javax.swing.JTextField();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelJornadas = new javax.swing.JLabel();
        jTextFieldJornadas = new javax.swing.JTextField();
        jLabelHabitacion = new javax.swing.JLabel();
        jCheckBoxHabitacion = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButtonReserva = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reserva Salón Habana");

        jLabel1.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jLabel1.setText("Salón Habana");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NombreCliente.setText("Nombre:*");

        TelefonoCliente.setText("Teléfono:*");

        Telefono.setToolTipText("Introduce un número de contacto");
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        LabelApellido1.setText("Primer Apellido:*");

        Apellido1.setToolTipText("Introduce el primer apellido del titular de la reserva");
        Apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido1ActionPerformed(evt);
            }
        });
        Apellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Apellido1KeyTyped(evt);
            }
        });

        LabelApellido2.setText("Segundo Apellido:");

        Apellido2.setToolTipText("Introduce el segundo apellido del titular de la reserva (opcional)");
        Apellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Apellido2KeyTyped(evt);
            }
        });

        jLabelFecha.setText("Fecha:*");

        jLabelTipo.setText("Tipo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Congreso", "Jornada", "Banquete" }));
        jComboBox1.setToolTipText("Selecciona el tipo de evento");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelPersonas.setText("Nº Personas:*");

        jTextFieldPersonas.setToolTipText("Introduce el número de personas que acudirán al evento");
        jTextFieldPersonas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPersonasKeyTyped(evt);
            }
        });

        jDateChooserFecha.setToolTipText("Introduce la fecha deseada de la reserva");
        jDateChooserFecha.setMinSelectableDate(new Date());

        jTextFieldNombre.setToolTipText("Introduce el nombre del titular de la reserva");
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jLabelJornadas.setText("Nº Jornadas:*");

        jTextFieldJornadas.setToolTipText("Introduce Nº de jornadas del congreso");
        jTextFieldJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJornadasActionPerformed(evt);
            }
        });
        jTextFieldJornadas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldJornadasKeyTyped(evt);
            }
        });

        jLabelHabitacion.setText("Habitación:");

        jCheckBoxHabitacion.setToolTipText("Seleccionar si necesita una habitación");
        jCheckBoxHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHabitacionActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de cocina:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No precisa", "Bufé", "Carta", "Pedir cita con el chef" }));
        jComboBox2.setToolTipText("Seleccione el tipo de cocina que desee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NombreCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelApellido1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TelefonoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelFecha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelJornadas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelHabitacion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCheckBoxHabitacion)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelTipo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabelPersonas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelApellido2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreCliente)
                        .addComponent(jLabelFecha)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelApellido1)
                            .addComponent(Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipo))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelApellido2)
                    .addComponent(jLabelJornadas)
                    .addComponent(jTextFieldJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TelefonoCliente)
                        .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion))
                    .addComponent(jCheckBoxHabitacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPersonas)
                    .addComponent(jTextFieldPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jButtonReserva.setText("Hacer Reserva");
        jButtonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("*Campos obligatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonReserva)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(jButtonReserva)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void Apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Object resultado;
        resultado = jComboBox1.getSelectedItem();
        if( resultado == "Congreso"){
            jLabelHabitacion.setEnabled(true);
            jCheckBoxHabitacion.setEnabled(true);
            jLabelPersonas.setEnabled(true);
            jTextFieldPersonas.setEnabled(true);
        }
        else{
            jLabelHabitacion.setEnabled(false);
            jCheckBoxHabitacion.setEnabled(false);
            jLabelPersonas.setEnabled(false);
            jTextFieldPersonas.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String tlf = Telefono.getText();            
        if(c<'0' || c>'9' || tlf.length() >= 9){
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String cha = Character.toString(c);
        boolean resultado = cha.matches("[a-zA-ZñÑéóíúáÁÉÍÓÚ ]");
        String Caracteres = jTextFieldNombre.getText();
        if(resultado == false || Caracteres.length()>=10){
                evt.consume();
            } 
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void Apellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Apellido1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String cha = Character.toString(c);
        boolean resultado = cha.matches("[a-zA-ZñÑéóíúáÁÉÍÓÚ ]");
        String CaracteresApellido1 = Apellido1.getText();
        if(resultado == false || CaracteresApellido1.length()>=10){
           evt.consume();
        }
        
    }//GEN-LAST:event_Apellido1KeyTyped

    private void Apellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Apellido2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String cha = Character.toString(c);
        boolean resultado = cha.matches("[a-zA-ZñÑéóíúáÁÉÍÓÚ ]");
        String CaracteresApellido2 = Apellido2.getText();
        if(resultado == false || CaracteresApellido2.length()>=10){
                evt.consume();
            }
            
        
    }//GEN-LAST:event_Apellido2KeyTyped

    private void jButtonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservaActionPerformed
        // TODO add your handling code here:
        String Caracteres = jTextFieldNombre.getText();
        String CaracteresApellido1 = Apellido1.getText();
        String tlf = Telefono.getText();            
        String date = jDateChooserFecha.getDateFormatString();
        String personas = jTextFieldPersonas.getText();
        if((Caracteres.length() == 0 || CaracteresApellido1.length() == 0
                || tlf.length() == 0 || date.length() == 0 || personas.length() == 0)){
            JOptionPane.showMessageDialog(null, "Los campos con asterisco (*) son obligatorios");
        }
        else{
            JOptionPane.showMessageDialog(null, "Reserva realizada con éxito");

        }
    }//GEN-LAST:event_jButtonReservaActionPerformed

    private void jTextFieldJornadasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldJornadasKeyTyped
        // TODO add your handling code here:
                // TODO add your handling code here:
        char c = evt.getKeyChar();
        String jornadas = jTextFieldJornadas.getText();            
        if(c<'0' || c>'9' || jornadas.length() >= 3){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldJornadasKeyTyped

    private void jTextFieldPersonasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPersonasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String personas = jTextFieldPersonas.getText();            
        if(c<'0' || c>'9' || personas.length() >= 3){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPersonasKeyTyped

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jCheckBoxHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHabitacionActionPerformed

    private void jTextFieldJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJornadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJornadasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalonHabana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SalonHabana dialog = new SalonHabana(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido1;
    private javax.swing.JTextField Apellido2;
    private javax.swing.JLabel LabelApellido1;
    private javax.swing.JLabel LabelApellido2;
    private javax.swing.JLabel NombreCliente;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel TelefonoCliente;
    private javax.swing.JButton jButtonReserva;
    private javax.swing.JCheckBox jCheckBoxHabitacion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHabitacion;
    private javax.swing.JLabel jLabelJornadas;
    private javax.swing.JLabel jLabelPersonas;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldJornadas;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPersonas;
    // End of variables declaration//GEN-END:variables
}
